"use client";

import { useEffect, useState } from "react";
import { Archive, CheckCircle2, ChevronDown, SearchCheck } from "lucide-react";

export default function SeoCollaborations({ collaboratorId = "" }) {
  const [rows, setRows] = useState([]); const [archived, setArchived] = useState(false); const [open, setOpen] = useState(""); const [error, setError] = useState("");
  const load = () => fetch(`/api/seo-collaborations?archived=${archived}${collaboratorId ? `&collaborator=${collaboratorId}` : ""}`, { cache: "no-store" }).then(async (res) => { const body = await res.json(); if (!res.ok) throw new Error(body.message); setRows(body); }).catch((err) => setError(err.message));
  useEffect(() => { load(); }, [archived, collaboratorId]);
  const update = async (row, changes) => { const res = await fetch(`/api/seo-collaborations/${row._id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(changes) }); const body = await res.json(); if (!res.ok) return setError(body.message); load(); };
  return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col justify-between gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="rounded-xl bg-emerald-50 p-2.5 text-emerald-700"><SearchCheck className="h-5 w-5" /></span><div><h2 className="font-bold text-slate-900">Servizi SEO</h2><p className="text-sm text-slate-500">Checklist e avanzamento dei siti web.</p></div></div><button onClick={() => setArchived(!archived)} className="text-sm font-semibold text-slate-600 hover:text-slate-900">{archived ? "Mostra attive" : "Mostra archiviate"}</button></div>{error && <p className="m-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="divide-y divide-slate-100">{rows.map((row) => <article key={row._id}><button onClick={() => setOpen(open === row._id ? "" : row._id)} className="flex w-full items-center justify-between gap-4 p-5 text-left"><div className="min-w-0"><p className="truncate font-bold text-slate-900">{row.aziendaRagioneSociale}</p><p className="text-sm text-slate-500">Web designer: {row.webDesigner?.nome} {row.webDesigner?.cognome}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-bold text-emerald-700">{row.percentuale}%</span><ChevronDown className={`h-5 w-5 transition ${open === row._id ? "rotate-180" : ""}`} /></div></button>{open === row._id && <div className="border-t border-slate-100 bg-slate-50/60 p-5"><div className="mb-4 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${row.percentuale}%` }} /></div><div className="space-y-3">{row.checklist.map((task) => <div key={task.key} className="rounded-xl border border-slate-200 bg-white p-3"><label className="flex cursor-pointer items-start gap-3"><input type="checkbox" className="mt-1 h-4 w-4" checked={task.completata} onChange={(e) => update(row, { checklist: row.checklist.map((item) => item.key === task.key ? { ...item, completata: e.target.checked } : item) })} /><span className={task.completata ? "text-slate-500 line-through" : "font-medium text-slate-800"}>{task.label}</span></label></div>)}</div>{row.percentuale === 100 && !row.archiviata && <button onClick={() => update(row, { archiviata: true })} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white"><Archive className="h-4 w-4" /> Archivia completata</button>}{row.archiviata && <p className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4" /> Collaborazione archiviata</p>}</div>}</article>)}{!rows.length && <p className="p-8 text-center text-slate-500">Nessuna collaborazione SEO {archived ? "archiviata" : "attiva"}.</p>}</div></section>;
}
