// Dati dispense estratti dalla board Trello "Dispensa Hoon"
// Ogni categoria rappresenta un tipo di attività con i relativi argomenti da trattare

export const dispensaCategorie = [
  {
    categoria: "Bar",
    icona: "🍸",
    items: [
      "Storia / chi siamo",
      "Dove siamo",
      "Contatti",
      "Logo",
      "Motto",
      "Il nostro locale",
      "I nostri servizi",
      "Orari",
      "Figure professionali",
      "La nostra clientela",
      "Rubrica: i nostri cocktail",
      "Rubrica: i nostri vini",
      "Rubrica: cibo + cocktail",
      "Serate",
      "Cucina",
      "Ingresso disabili",
      "Collaborazioni aziende locali",
      "Rubrica: colazione del giorno",
      "Video a tema festa/serata",
      "Allergie",
      "Dicono di noi riviste/blog/recensioni",
    ],
  },
  {
    categoria: "Ristorante",
    icona: "🍽️",
    items: [
      "Storia / chi siamo",
      "Dove siamo",
      "Contatti",
      "Motto",
      "Logo",
      "Il nostro locale",
      "I nostri servizi",
      "Orari",
      "Figure professionali",
      "La nostra clientela",
      "Rubrica: i nostri piatti",
      "Rubrica: i nostri vini",
      "Rubrica: cibo + vino",
      "Serate",
      "Cucina",
      "Rubrica: lo chef consiglia",
      "Rubrica: i nostri piatti",
      "Occasioni importanti",
      "Materia prima + risultato finale",
      "Ingresso disabili",
      "Collaborazioni aziende locali",
      "Riprese aeree",
      "Pranzo",
      "Video a tema festa/serata",
      "Piano bar",
      "Antipasti",
      "Dolci",
      "Allergie",
      "Dicono di noi riviste/blog/recensioni",
    ],
  },
  {
    categoria: "Pizzeria",
    icona: "🍕",
    items: [
      "Storia / chi siamo",
      "Dove siamo",
      "Contatti",
      "Motto",
      "Logo",
      "Come arrivare?",
      "Il nostro locale",
      "I nostri servizi",
      "Orari",
      "Figure professionali",
      "La nostra clientela",
      "Consegna a casa",
      "Il nostro impasto",
      "Ingredienti",
      "Rubrica: le nostre pizze",
      "Ingresso disabili",
      "Collaborazioni aziende locali",
      "Video a tema festa/serata",
      "Rubrica: bevande",
      "Antipasti",
      "Dolci",
      "Allergie",
      "Dicono di noi riviste/blog/recensioni",
    ],
  },
  {
    categoria: "Poke",
    icona: "🥗",
    items: [
      "Storia / chi siamo",
      "Dove siamo",
      "Contatti",
      "Motto",
      "Logo",
      "Il nostro locale",
      "I nostri servizi",
      "Orari",
      "Figure professionali",
      "La nostra clientela",
      "Consegna a casa",
      "I nostri prodotti",
      "Ingredienti",
      "Rubrica: i nostri poke",
      "Ingresso disabili",
      "Collaborazioni aziende locali",
      "Video a tema festa/serata",
      "Poke + bibita",
      "Allergie",
      "Bubble tea",
      "Bevande",
      "Come arrivare?",
      "Sostenibilità merch",
      "Dicono di noi riviste/blog/recensioni",
    ],
  },
  {
    categoria: "Palestra",
    icona: "🏋️",
    items: [
      "Storia / chi siamo",
      "Dove siamo",
      "Contatti",
      "Motto",
      "Logo",
      "Il nostro locale",
      "Come arrivare?",
      "Docce e spogliatoi",
      "Macchinari e attrezzi",
      "I nostri servizi",
      "Corsi",
      "Dettaglio corsi",
      "Orari",
      "Figure professionali",
      "Ingresso disabili",
      "Challenge",
      "Comunicazioni",
      "Collaborazioni aziende locali",
      "Video a tema festa/serata",
      "Vendita merchandising",
      "Dicono di noi riviste/blog/recensioni",
    ],
  },
  {
    categoria: "Hotel & Affittacamere",
    icona: "🏨",
    items: [
      "Storia / chi siamo",
      "Dove siamo",
      "Contatti",
      "Motto",
      "Logo",
      "La nostra struttura",
      "Come arrivare?",
      "Orari check in/out",
      "I nostri servizi",
      "Figure professionali",
      "La nostra clientela",
      "Ingresso disabili",
      "Collaborazioni aziende locali",
      "Collaborazioni servizi esterni",
      "Riprese aeree",
      "Stanze",
      "Dettagli stanze",
      "Palestra",
      "Piscina",
      "Spa",
      "Tramonto",
      "Alba",
      "Offerte + combo",
      "Servizio con modelli",
      "Video a tema festa/serata",
      "Eventi & meeting",
      "Dicono di noi riviste/blog/recensioni",
    ],
  },
  {
    categoria: "Industria",
    icona: "🏭",
    items: [
      "Storia / chi siamo",
      "Dove siamo",
      "Contatti",
      "Motto",
      "Logo",
      "La nostra struttura",
      "Come arrivare?",
      "Orari",
      "I nostri servizi",
      "Figure professionali",
      "La nostra clientela",
      "Collaborazioni aziende locali",
      "Collaborazioni servizi esterni",
      "Riprese aeree",
      "Macchinari",
      "Video a tema festa/serata",
      "Dicono di noi riviste/blog/recensioni",
    ],
  },
  {
    categoria: "Scuola/Università",
    icona: "🎓",
    items: [
      "Storia / chi siamo",
      "Dove siamo",
      "Contatti",
      "Motto",
      "Logo",
      "La nostra struttura",
      "Come arrivare?",
      "Orari",
      "I nostri servizi",
      "Figure professionali",
      "La nostra clientela",
      "Collaborazioni aziende locali",
      "Collaborazioni servizi esterni",
      "Rubrica: Parla il prof",
      "I nostri corsi",
      "Spiegazione dei corsi",
      "Foto/video Lauree",
      "Dicono di noi riviste/blog/recensioni",
    ],
  },
  {
    categoria: "Telefonia & Riparazioni",
    icona: "📱",
    items: [
      "Storia / chi siamo",
      "Dove siamo",
      "Contatti",
      "Motto",
      "Logo",
      "La nostra struttura",
      "Come arrivare?",
      "Orari",
      "I nostri servizi",
      "Figure professionali",
      "La nostra clientela",
      "Collaborazioni aziende locali",
      "Collaborazioni servizi esterni",
      "Rubrica: come riparare",
      "Rubrica: nuove uscite",
      "I 3/5 consigli",
      "Linea Mobile come scegliere",
      "Linea fissa come scegliere",
      "Operatori disponibili",
      "Spid",
      "Permuta telefono",
      "Video a tema festa/serata",
      "Dicono di noi riviste/blog/recensioni",
    ],
  },
  {
    categoria: "Profumeria",
    icona: "💐",
    items: [
      "Storia / chi siamo",
      "Dove siamo",
      "Contatti",
      "Motto",
      "Logo",
      "La nostra struttura",
      "Come arrivare?",
      "Orari",
      "I nostri servizi",
      "Figure professionali",
      "La nostra clientela",
      "Collaborazioni aziende locali",
      "Collaborazioni servizi esterni",
      "Rubrica: note olfattive",
      "Rubrica: profumi",
      "I 3/5 consigli",
      "Note olfattive",
      "Come scegliere un profumo",
      "Profumi stagionali",
      "Make up",
      "Tutorial make up",
      "Make up feste/occasioni",
      "Dicono di noi riviste/blog/recensioni",
    ],
  },
];
